### ISSUE TITLE
Getting "An open statement already exists" while data is correct

### ISSUE THREAD

**Issue by mpmlj** [johnnadratowski/golang-neo4j-bolt-driver#25]
Hi,

Thanks for working on the bolt driver!

I observe the following issue: the following query will return correct result if run with relatively large intervals. However, if interval between queries decrease to a certain level, the driver throws "Error #01: An open statement already exists".

How to reproduce:
1. Works fine if, for example, you'll have an endpoint/script that you'll be triggering manually. I could not reach low enough interval to catch the error.
2. However, if you'll run this endpoint via [wrk](https://github.com/wg/wrk), for example, as `wrk -c2 -d5s  http://localhost:9090/v0.1/posts/userlist/foo123456?p=1&ipp=12` you'll be able to get the error. Maybe concurrency?

Sample code:
````Go
var err error
	var IDs []string

	data, _, _, err := g.DB.QueryNeoAll(`
		MATCH (u:User)-[:POSTED]->(p:Post)
		WHERE u.id = {userId}
		RETURN p.id AS id
		ORDER BY p.created DESC
		SKIP {skip}
		LIMIT {limit}
		`,
		map[string]interface{}{
			"limit":  ipp,
			"skip":   page,
			"userId": userID,
		})
	if err != nil {
		return IDs, err
	}

	for _, row := range data {
		IDs = append(IDs, row[0].(string))
	}
	fmt.Printf("IDs: %#v\n", IDs)

	return IDs, nil
````

Here's how I instantiate the connection to be available throughout the whole packages of my application:

````Go
var (
	DB bolt.Conn
)

// Connect established a connection to the graph database using parameters specified in the config.
func Connect() error {
	var err error
	driver := bolt.NewDriver()
	DB, err = driver.OpenNeo(config.Get("neo4j.connString"))

	return err
}
````

Any ideas are appreciated!
Thanks
D

**Comment by johnnadratowski** [comment]
@mpmlj - Sorry for the late response here.  This is an interesting one.  Do you have a full stack trace, and/or an example script?

**Comment by tristanmccarthy** [comment]
Hey,

I'm new to go and neo and have been enjoying playing with both thanks to this driver, all was going well until I hit the same problem mentioned in this ticket.
My code looks very similar to that shared in the original ticket. 
I have a go web service using the bolt driver to interact with neo, then an angular2 web front end calling the service. I got to a point where my front end was making two calls to the back end at the same time to get different sets of data and get "An open statement already exists" from the second call.

Full error:

`2017/05/04 12:34:47 An open statement already exists

 Stack Trace:

goroutine 38 [running]:
runtime/debug.Stack(0x730a7f, 0x20, 0x0)
	C:/Go/src/runtime/debug/stack.go:24 +0x80
github.com/johnnadratowski/golang-neo4j-bolt-driver/errors.New(0x730a7f, 0x20, 0x0, 0x0, 0x0, 0xc0420fb5a0)
	C:/Users/tris/Documents/go-workspace/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/errors/errors.go:21 +0x83
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).prepare(0xc0420e4000, 0x72fee1, 0x1e, 0x6bb9c0, 0xc042106301, 0x8ac270)
	C:/Users/tris/Documents/go-workspace/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:494 +0x1c2
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).PrepareNeo(0xc0420e4000, 0x72fee1, 0x1e, 0xd, 0x2, 0x2, 0x10)
	C:/Users/tris/Documents/go-workspace/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:477 +0x46
github.com/opencredo/huranga/skillservice/service/dbclient.(*NeoDBClient).GetTechs(0xc042037190, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Users/tris/Documents/go-workspace/src/github.com/opencredo/huranga/skillservice/service/dbclient/neoclient.go:58 +0xf7
github.com/opencredo/huranga/skillservice/service.GetTechs(0x864220, 0xc04211e8c0, 0xc042110e00)
	C:/Users/tris/Documents/go-workspace/src/github.com/opencredo/huranga/skillservice/service/handlers.go:34 +0x4e
net/http.HandlerFunc.ServeHTTP(0x73adf8, 0x864220, 0xc04211e8c0, 0xc042110e00)
	C:/Go/src/net/http/server.go:1942 +0x4b
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0420f4140, 0x864220, 0xc04211e8c0, 0xc042110e00)
	C:/Users/tris/Documents/go-workspace/src/github.com/gorilla/mux/mux.go:114 +0x113
github.com/rs/cors.(*Cors).Handler.func1(0x864220, 0xc04211e8c0, 0xc042110c00)
	C:/Users/tris/Documents/go-workspace/src/github.com/rs/cors/cors.go:190 +0xf0
net/http.HandlerFunc.ServeHTTP(0xc0420f6cc0, 0x864220, 0xc04211e8c0, 0xc042110c00)
	C:/Go/src/net/http/server.go:1942 +0x4b
net/http.serverHandler.ServeHTTP(0xc04212a0b0, 0x864220, 0xc04211e8c0, 0xc042110c00)
	C:/Go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc04210cbe0, 0x864720, 0xc0420f8c00)
	C:/Go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
	C:/Go/src/net/http/server.go:2668 +0x2d5`

Any direction you could give would be appreciated.

**Comment by saeedsh** [comment]
I have the same situation. As I found we are using Thread unsafe Connection method in a mutithread environment. Which is not going to work properly, even by using connection pool. I recommend to synchronize usage of each connection. For example:

`
var _driver neoBolt.Driver
var _conn neoBolt.Conn

func init() {
	_driver = neoBolt.NewDriver()
	_conn, _ = _driver.OpenNeo(_boltURL)
}

var m sync.Mutex
func getData(query string, params map[string]interface{}) string{

	m.Lock()
	data, _, _, err  := _conn.QueryNeoAll(query, params)
	m.Unlock()
        ...
	return string(resp)
}
`

**Comment by sh0umik** [comment]
`` This Problem Simply Means The Connection Is Still Opens and Bolt is not able to Prepare another connection if one still open.

You have to Close the connection After preparing and executing Pipeline or Batch Query  

```
	err = pipeline.Close() // Or Batch Execution Object
	if err != nil {
		panic(err)
	}
```

That will fix the problem

**Comment by collisonchris** [comment]
I've run into this a few times and carefully looking at how I was setting up the execution lead me to follow the same path @sh0umik did, closing the statment object before executing anther is the best way to deal with this issue. I ended up writing a generic parameterized execution function:

```
func executeParameterizedQuery(conn bolt.Conn, queryString string, params map[string]interface{}) (bolt.Result, error) {
	stmt, err := conn.PrepareNeo(queryString)
	if err != nil {
		log.Error(err)
		return nil, err
	}
	result, e := stmt.ExecNeo(params)
	if e != nil {
		log.Error(e)
		return nil, e
	}
	stmt.Close()
	return result, nil
}
```

**Comment by vikashvverma** [comment]
> I've run into this a few times and carefully looking at how I was setting up the execution lead me to follow the same path @sh0umik did, closing the statment object before executing anther is the best way to deal with this issue. I ended up writing a generic parameterized execution function:
> 
> ```
> func executeParameterizedQuery(conn bolt.Conn, queryString string, params map[string]interface{}) (bolt.Result, error) {
> 	stmt, err := conn.PrepareNeo(queryString)
> 	if err != nil {
> 		log.Error(err)
> 		return nil, err
> 	}
> 	result, e := stmt.ExecNeo(params)
> 	if e != nil {
> 		log.Error(e)
> 		return nil, e
> 	}
> 	stmt.Close()
> 	return result, nil
> }
> ```

Are you still able to read the data?
I believe if you close the statement then you won't be able to read the result.
