### ISSUE TITLE
Couldn't connect to neo4j 

### ISSUE THREAD

**Issue by krishnadubagunta** [johnnadratowski/golang-neo4j-bolt-driver#48]
Hello, 

I'm facing problem while connecting to neo4j. I started the neo4j database and is running at 127.0.0.1:7687/ as usual. 

```
panic: An error occurred initializing connection
	An error occurred decoding ack failure message response
		Couldn't read expected bytes for message length. Read: 0 Expected: 2.
Internal Error(*errors.errorString):EOF

 Stack Trace:

goroutine 1 [running]:
runtime/debug.Stack(0x1234d90, 0x46, 0xc420053908)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/johnnadratowski/golang-neo4j-bolt-driver/errors.Wrap(0x131f8c0, 0xc420010050, 0x1234d90, 0x46, 0xc420053908, 0x1, 0x1, 0xc420010050)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/errors/errors.go:38 +0x1a0
github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding.Decoder.read(0x131f900, 0xc420098000, 0xc4200aa460, 0x1012018, 0x70, 0x120bac0)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding/decoder.go:45 +0x471
github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding.Decoder.Decode(0x131f900, 0xc420098000, 0xc4200aa460, 0xffff, 0x11f95c0, 0x135ade8, 0x0)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/encoding/decoder.go:93 +0x43
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).ackFailure(0xc420098000, 0xc4200a0090, 0xc420053ac8, 0x1)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:402 +0x1bb
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).consume(0xc420098000, 0xc420098000, 0xc4200aa000, 0xc4200affff, 0x12087c0)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:555 +0x177
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).sendInit(0xc420098000, 0x0, 0x0, 0x0, 0x0)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:611 +0x35f
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltConn).initialize(0xc420098000, 0xc420098000, 0x4)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:291 +0x168
github.com/johnnadratowski/golang-neo4j-bolt-driver.newBoltConn(0x122b64b, 0x15, 0xc42000e030, 0x11f82c0, 0x101, 0xc42000e030)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/conn.go:102 +0xfd
github.com/johnnadratowski/golang-neo4j-bolt-driver.(*boltDriver).OpenNeo(0xc42000e030, 0x122b64b, 0x15, 0xc420053e20, 0x1029e88, 0x30, 0x30)
	/Volumes/Projects/Golang/src/github.com/johnnadratowski/golang-neo4j-bolt-driver/driver.go:62 +0x3f
main.main()
	/Volumes/Projects/GoLang/src/github.com/krishnadubagunta/sampleTrial/main.go:12 +0x65


goroutine 1 [running]:
main.main()
	/Volumes/Projects/GoLang/src/github.com/krishnadubagunta/sampleTrial/main.go:14 +0xfae

Process finished with exit code 2
```
I get this error when I run your sample slowNClean program!

Please help me setting this up?

**Comment by gvilli** [comment]
Hi, probably my reply comes too late, however I got the same error; in my case the problem was that I wrote the http port 7474 rather then the bolt port 7687 in the connection URL, i.e.

	neo4jURL = "bolt://neo4j:somepassword@localhost:7474"

instead of 

	neo4jURL = "bolt://neo4j:somepassword@localhost:7687"

**Comment by umerm-work** [comment]
@gvilli thanks for the solution. I was facing same issue.

**Comment by gotoolkits** [comment]
fixed it!

To modify neo4j.conf file:

# To disable authentication, uncomment this line
dbms.security.auth_enabled=false

Hope it help for u.

**Comment by scott-wilson** [comment]
@krishnadubagunta This good, or still running into problems?

**Comment by krishnadubagunta** [comment]
Should probably be good. I can close this issue for now.  And re-open when and if I run into it again. Cool ?

**Comment by scott-wilson** [comment]
Sounds good to me.
